"""create produtos table

Revision ID: c51550fb5cf1
Revises: 40bdd35e8f2d
Create Date: 2024-05-24 05:15:03.074994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51550fb5cf1'
down_revision: Union[str, None] = '40bdd35e8f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('susep', sa.String(), nullable=False),
    sa.Column('expiracao_de_venda', sa.DateTime(), nullable=False),
    sa.Column('valor_minimo_aporte_inicial', sa.Float(), nullable=False),
    sa.Column('valor_minimo_aporte_extra', sa.Float(), nullable=False),
    sa.Column('idade_de_entrada', sa.Integer(), nullable=False),
    sa.Column('idade_de_saida', sa.Integer(), nullable=False),
    sa.Column('carencia_inicial_de_resgate', sa.Integer(), nullable=False),
    sa.Column('carencia_entre_resgates', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos')
    # ### end Alembic commands ###
