name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Docker build
        run: docker-compose build

      - name: Docker up
        run: docker-compose up -d

      - name: run coverage
        run: docker-compose run --rm web poetry run pytest --cov=api --cov-report=term-missing --cov-report=html

      - name: upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: htmlcov/

      - name: Fix permissions and move coverage report
        run: |
          sudo chmod -R 777 htmlcov
          mkdir -p coverage-report
          cp -r htmlcov/* coverage-report/

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./coverage-report
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
