name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Docker build
        run: docker-compose build

      - name: Docker up
        run: docker-compose up

      - name: run coverage
        run: docker-compose run --rm web poetry run pytest --cov=api --cov-report=term-missing --cov-report=html

      - name: upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: htmlcov/

      - name: deploy to github page
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./htmlcov
